### ISSUE TITLE
Sails v1.0.0-45

### ISSUE THREAD

**Issue by mancarv** [arrowfunxtion/sails-doc#1]
Hi, I'm using sails v1 and don't know if it is the problem but I can't make it work, in the root path of the project I execute sails-doc and the result is:

```
Making docs...
Err: Error: Command failed: /usr/lib/node_modules/sails-doc/node_modules/jsdoc/jsdoc.js /home/project/test/api/** /home/project/test/config/routes.js -c /usr/lib/node_modules/sails-doc/lib/jsdoc.json -t /usr/lib/node_modules/sails-doc/lib/docdash-category --destination /home/project/test/assets/docs
undefined:124
 var method = doc.actionName.split('.')[1] 
                             ^

TypeError: Cannot read property 'split' of undefined
    at eval (eval at _.template (/usr/lib/node_modules/sails-doc/node_modules/underscore/underscore.js:1454:20), <anonymous>:124:30)
    at Array.forEach (<anonymous>)
    at exports.Template.eval (eval at _.template (/usr/lib/node_modules/sails-doc/node_modules/underscore/underscore.js:1454:20), <anonymous>:10:10)
    at exports.Template.template (/usr/lib/node_modules/sails-doc/node_modules/underscore/underscore.js:1461:21)
    at exports.Template.partial (/usr/lib/node_modules/sails-doc/node_modules/jsdoc/lib/jsdoc/template.js:55:29)
    at exports.Template.render (/usr/lib/node_modules/sails-doc/node_modules/jsdoc/lib/jsdoc/template.js:69:24)
    at generate (/usr/lib/node_modules/sails-doc/lib/docdash-category/publish.js:228:21)
    at /usr/lib/node_modules/sails-doc/lib/docdash-category/publish.js:695:13
    at Array.forEach (<anonymous>)
    at Object.exports.publish (/usr/lib/node_modules/sails-doc/lib/docdash-category/publish.js:692:39)
    at Object.module.exports.cli.generateDocs (/usr/lib/node_modules/sails-doc/node_modules/jsdoc/cli.js:448:35)
    at Object.module.exports.cli.processParseResults (/usr/lib/node_modules/sails-doc/node_modules/jsdoc/cli.js:399:20)
    at module.exports.cli.main (/usr/lib/node_modules/sails-doc/node_modules/jsdoc/cli.js:240:14)
    at Object.module.exports.cli.runCommand (/usr/lib/node_modules/sails-doc/node_modules/jsdoc/cli.js:189:5)
    at /usr/lib/node_modules/sails-doc/node_modules/jsdoc/jsdoc.js:105:9
    at Object.<anonymous> (/usr/lib/node_modules/sails-doc/node_modules/jsdoc/jsdoc.js:106:3)
  ```

**Comment by arrowfunxtion** [comment]
sails-doc was created to work with sails version 0.12. We haven't support sails v1 yet. Sails v1 is under beta now.

**Comment by mancarv** [comment]
I find the problem, it wasn't the version. I had a route like 'GET /' : 'action', it seems like is strict necessary that it have a controller. I also notice that if there is a substructure of directories inside 'controllers' doesn't work, need to add the flag '-r' or '--recurse'.

**Comment by nicolapalavecino** [comment]
I happen to have the same problem as yours (using sails 1.0.2). Using `sails-doc -r` didn't work either. Thank you!
